# Conda environment for the mhw3d-detection project
name: mhw3d
channels:
  - conda-forge
dependencies:
  # Core scientific libraries
  - python=3.10
  - dask
  - netcdf4
  - numpy
  - pandas
  - scipy
  - xarray

  # Performance
  - bottleneck
  - flox
  - zarr

  # Testing
  - pytest

  # Interactive development and plotting
  - jupyterlab
  - notebook
  - ultraplot # proplot deprecated
