# Conda environment for the mhw3d-detection project
name: mhw3d
channels:
  - conda-forge
dependencies:
  # Core scientific libraries
  - python=3.10
  - numpy
  - pandas
  - xarray
  - dask
  - bottleneck
  - netcdf4
  - scipy

  # Testing
  - pytest

  # Interactive development and plotting
  - jupyterlab
  - notebook
  - proplot
